// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEW0H4PjrxD6H6IQwppKORIOHH7MbiNCw',
    appId: '1:189110373605:web:40f62bf935bdc4c9b9d80c',
    messagingSenderId: '189110373605',
    projectId: 'ats-resume-app-7a481',
    authDomain: 'ats-resume-app-7a481.firebaseapp.com',
    storageBucket: 'ats-resume-app-7a481.firebasestorage.app',
    measurementId: 'G-VVX7FKQ5PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArgYRf45y9fQkaCVItF4j5Z4-WMmV978Q',
    appId: '1:189110373605:android:53425070ca2fb9edb9d80c',
    messagingSenderId: '189110373605',
    projectId: 'ats-resume-app-7a481',
    storageBucket: 'ats-resume-app-7a481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqud0hz-BjRJHZe-ARicHjkdeseIYQ4FA',
    appId: '1:189110373605:ios:366ab1fb3bbab56cb9d80c',
    messagingSenderId: '189110373605',
    projectId: 'ats-resume-app-7a481',
    storageBucket: 'ats-resume-app-7a481.firebasestorage.app',
    iosBundleId: 'com.example.atsResumeBuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqud0hz-BjRJHZe-ARicHjkdeseIYQ4FA',
    appId: '1:189110373605:ios:366ab1fb3bbab56cb9d80c',
    messagingSenderId: '189110373605',
    projectId: 'ats-resume-app-7a481',
    storageBucket: 'ats-resume-app-7a481.firebasestorage.app',
    iosBundleId: 'com.example.atsResumeBuilder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEW0H4PjrxD6H6IQwppKORIOHH7MbiNCw',
    appId: '1:189110373605:web:9ca6a68738c9fbe9b9d80c',
    messagingSenderId: '189110373605',
    projectId: 'ats-resume-app-7a481',
    authDomain: 'ats-resume-app-7a481.firebaseapp.com',
    storageBucket: 'ats-resume-app-7a481.firebasestorage.app',
    measurementId: 'G-494QHPW4B6',
  );
}
